# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
array = np.random.randint(0,10,5)
print(array)
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
sıralı_array = np.sort(array)
print(sıralı_array)

[3 1 2 9 0]
[0 1 2 3 9]


# Problem 2

In [27]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
array1 = np.array([10,15,30,45,60])
print(array1)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
array2 = np.arange(5,16,1)
print(array2)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
array3 = np.arange(50,101,5)
print(array3)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
array4 = np.zeros(10)
print(array4)
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
array5 = np.ones(10)
print(array5)
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
array6 = np.linspace(0,100,5)
print(array6)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
array7 = np.random.randint(10,31,5)
print(array7)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
array8 = np.random.uniform(-1,1,10)
print(array8)
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matris = np.random.randint(10,51,(3,5))
print(matris)
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satır_toplam = matris.sum(axis=1)
sütun_toplam = matris.sum(axis=0)
print(satır_toplam)
print(sütun_toplam)
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
max = matris.max()
min = matris.min()
average = matris.mean()
print(max)
print(min)
print(average)
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
max_indeks = np.unravel_index(matris.argmax(), matris.shape)
print(max_indeks)
# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
array9 = np.arange(10,21,1)
print(array9[:3])
# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(array9[::-1])
# 15- Üretilen matrisin ilk satırını seçiniz.
print(matris[0])
# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(matris[1,2])
# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(matris[:,0])
# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(matris**2)
# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
matris2 = np.random.randint(-50,51,(4,5))
print(matris2)
pozitif_cift_sayilar = matris2[(matris2 > 0) & (matris2 % 2 == 0)]
print(pozitif_cift_sayilar)

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 50  55  60  65  70  75  80  85  90  95 100]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[28 28 11 30 30]
[ 0.58560494 -0.09729299  0.89919026  0.78547448 -0.2096153   0.59099416
  0.36586728  0.60398211 -0.04659269 -0.31411345]
[[46 32 25 16 32]
 [26 31 50 11 26]
 [49 43 17 12 16]]
[151 144 137]
[121 106  92  39  74]
50
11
28.8
(np.int64(1), np.int64(2))
[10 11 12]
[20 19 18 17 16 15 14 13 12 11 10]
[46 32 25 16 32]
50
[46 26 49]
[[2116 1024  625  256 1024]
 [ 676  961 2500  121  676]
 [2401 1849  289  144  256]]
[[  5  16   4  -2 -33]
 [-39  43  -8  30  49]
 [-39  26 -16 -31 -40]
 [-18 -28 -23 -30  17]]
[16  4 30 26]
