# Problem 1

In [29]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matris = np.random.randint(0,10,5)
print(matris)
# 3 - matris'in boyutunu öğrenin
boyut = matris.shape
print("Boyut =", boyut)
# 4 - matris'i yeniden boyutlandırın
yeni_boyut = matris.reshape(5,1)
print("Yeni boyutlandırma = \n", yeni_boyut)
# 5 - matris'in boyut sayısını öğrenin
boyut_sayısı = matris.ndim
print(boyut_sayısı)

[5 2 4 9 2]
Boyut = (5,)
Yeni boyutlandırma = 
 [[5]
 [2]
 [4]
 [9]
 [2]]
1


# Problem 2

In [30]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
matris = np.arange(1,10,2)
print(matris)
# 2 - Oluşturduğunuz matrisi parçalayın
pmatris = np.array_split(matris,2)
print(pmatris)
# 3 - Parçalanmış matrisleri birleştirin
bmatris = np.concatenate(pmatris)
print(bmatris)

[1 3 5 7 9]
[array([1, 3, 5]), array([7, 9])]
[1 3 5 7 9]


# Problem 3

In [31]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
matris = np.random.choice(np.arange(5,101,2),10,replace = False)
# 2 - matris'in özelliklerini inceleyin
boyut = matris.shape
boyutSayisi = matris.ndim
elemanSayisi = matris.size
veriTipi = matris.dtype
print("Matris :",matris)
print("Boyutu :", boyut)
print("Boyut sayısı:", boyutSayisi)
print("Eleman sayısı :", elemanSayisi)
print("Veri tipi:", veriTipi)


Matris : [35 95 65 99 51 75 67 27 15 61]
Boyutu : (10,)
Boyut sayısı: 1
Eleman sayısı : 10
Veri tipi: int64
